create table patients(
	patient_id uuid primary key,
	patient_name varchar(150) not null,
	patient_phone varchar(100) not null,
	patient_age int not null
);

create table doctors(
	doctor_id int generated by default as identity primary key,
	doctor_name varchar(200) not null,
	doctor_phone varchar(100) not null,
	specialization varchar(100) not null
);

create table appointments(
	appointment_id int generated by default as identity primary key,
	appointment_date date not null,
	patient_id uuid not null references patients(patient_id),
	doctor_id int not null references doctors(doctor_id),
	diagnosis varchar(150) not null,
	status varchar(50) not null,
	cost int not null
);

